### ISSUE TITLE
将Sources内的文件导进项目build的后，报错 ： Function builder attribute 'ViewBuilder' can only be applied to a property if it defines a getter

### ISSUE THREAD

**Issue by AganYa** [fatbobman/NavigationViewKit#3]
报错文件名：NavigationViewManager.swift

具体报错位置：@ViewBuilder var view: () -> AnyView

       public init(tag: String, animated: Bool, view: @escaping () -> AnyView) {
            self.tag = tag
            self.animated = animated
            self.view = view
        }

        let tag: String
        let animated: Bool
        @ViewBuilder var view: () -> AnyView  // build后，这里报错：Function builder attribute 'ViewBuilder' can only be applied to a property if it defines a getter
    }

Swift版本：5.3
工具版本：XCode 12
系统：Catalina  10.15.5

**Comment by fatbobman** [comment]
你好，因为 @ViewBuilder var view: () -> AnyView   的用法是Swift 5.4以后才支持的，所以在你的系统上报错了。我已经对其做了修改，目前应该可以兼容Swift 5.3了。

**Comment by AganYa** [comment]
你好，重新导进去后还是报错
在项目文件里导入库的时候
import NavigationViewKit  ，报错了:No such module 'NavigationViewKit'

请问有什么微信群或者QQ群嘛？可以一起讨论一下

**Comment by fatbobman** [comment]
导入后，你将Package添加到Target中了吗？
wx：fatbobman
