### ISSUE TITLE
作者你好，想请教一个路由跳转的问题

### ISSUE THREAD

**Issue by BugMonkey** [fatbobman/NavigationViewKit#4]
需求是这样：PageA -> PageB -> PageC,此时跳转PageD,但是PageB、PageC 都要退出，即变为PageA -> PageD;
现在实现的方法是以PageA为root，popToRoot 后，再pushView(tag: "root"){ PageD()} ，这样虽然可以实现，但是会有一个先切回到PageA的过程，请问有没有其他实现方法呢

**Comment by fatbobman** [comment]
你好，目前没有什么太好的解决方案。
不过如果仅就你现在的情况来说，是否可以考虑，屏蔽原来的 pageD 的返回按钮，自己添加一个，让pageD直接返回到 root。这样就可以在 pageC 上直接 跳转到 pageD上，而又能从 pageD 上直接返回 PageA

**Comment by BugMonkey** [comment]
> 屏蔽 pageD 的返回跳转root，root的页面状态会和先前不一样。如果swiftui能够类似Android的singleTop就好了，真令人头大

**Comment by fatbobman** [comment]
你好，目前没有什么太好的解决方案。
不过如果仅就你现在的情况来说，是否可以考虑，屏蔽原来的 pageD 的返回按钮，自己添加一个，让pageD直接返回到 root。这样就可以在 pageC 上直接 跳转到 pageD上，而又能从 pageD 上直接返回 PageA
